# # vim: set expandtab ai :

version: "2"

services:
    # For building locally.
    builder:
        build: .
        environment:
            # HACK: allows pktvisor to see its conf files outside of /etc
            ETCDIRE: "/builder"
        volumes:
            - ./src:/builder
    
    # For building a Debian package for release.
    release:
        image: pktvisor_builder
        volumes:
            - ./src:/builder
        working_dir: /builder
        # HACK: Stupid dpkg builder can only output to parent dir so we copy the result
        # so as to expose it for the caller of this docker.
        command: [/bin/sh, -c, "dpkg-buildpackage -us -uc -b && cp ../pktvisor_*.deb /builder/"]

    # For running locally.  Requires that the builder image be built.
    pktvisor:
        image: pktvisor_builder
        cap_add:
            # Required when running in docker.
            - IPC_LOCK
        volumes:
            - ./src:/builder
        entrypoint: /builder/pktvisor/pktvisor

